### ISSUE TITLE
Doesn't work, what am I missing?

### ISSUE THREAD

**Issue by VictorZakharov** [YuryScherbakov/ngrx-busy#1]
Tried to set this up, but it doesn't seem to do anything.
Do I have to have an interceptor as described here https://www.npmjs.com/package/ngrx-busy?
Meaning it's not intended to work with just any observable?

I created a stackblitz to illustrate.

Editable code:
https://stackblitz.com/edit/angular-ivy-8qakxb?file=src/app/app.component.html

Demo:
https://angular-ivy-8qakxb.stackblitz.io

![image](https://user-images.githubusercontent.com/8978766/161396768-78f3f54f-2aa1-41b9-a826-bdd17b27fd5f.png)

**Comment by yury-sch** [comment]
@VictorZakharov Sorry for loooong answer. As you know any observable may be hot and cold. So, we don't known is observable completed or not. To provide information about payload interval you should wrap your observable with `pushBusy` function. So this will work when you change your code to `return pushBusy(of(v).pipe(delay(2000)));`
